# --- !Ups

create table "exams" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "level" int not null,
  "date" DATE not null,
);

# --- !Downs

drop table "exams" if exists;
